# Generated by Django 5.0.1 on 2024-08-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_date',
        ),
    ]
