# Generated by Django 5.0.1 on 2024-08-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_remove_match_match_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_team_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
