# Generated by Django 5.0.1 on 2024-08-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_alter_match_away_team_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_team_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='first_goal_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_score',
            field=models.IntegerField(default=0),
        ),
    ]
